version: '3.8'

services:
  app:
    build: .
    container_name: kennitoring
    restart: always
    privileged: true 
    network_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/sys:ro
      - /proc:/proc:ro
    environment:
      - PROCFS_PATH=/proc
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"